### PR TITLE
Adding 'advanced-feature-usage' metric to telemeter configuration

### PR DESCRIPTION
**Pull request by aruniiird**
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

### CODE REVIEW

**Comment by matej-g** [comment]
@aruniiird you might need to run `make manifests` locally and committing new changes, the change needs to be propagated to our YAML file as well.

**Comment by rexagod** [comment]
I'm not seeing any changes on `make manifests`. I think there's some additional targets that need to be run here. 🤔 

```
┌[rexagod@nebuchadnezzar] [/dev/pts/0] [a] 
└[~/repositories/configuration]> make manifests
>>>>> Running format
/home/rexagod/go/bin//jsonnetfmt-v0.18.0 -n 2 --max-blank-lines 2 --string-style s --comment-style s -i ./configuration/observatorium/metric-federation-rules.libsonnet ./configuration/observatorium/queries.libsonnet ./configuration/observatorium/ruler-remote-write.libsonnet ./configuration/observatorium/tenants.libsonnet ./observability/config.libsonnet ./observability/dashboards/observatorium-api.libsonnet ./observability/dashboards/telemeter-canary.libsonnet ./observability/dashboards/telemeter.libsonnet ./observability/dashboards/observatorium-api-logs.libsonnet ./observability/dashboards/slo.libsonnet ./observability/grafana.jsonnet ./observability/observatorium-logs/loki-tenant-alerts.libsonnet ./observability/observatorium-logs/loki-overview.libsonnet ./observability/grafana-obs-logs.jsonnet ./observability/prometheusrules.jsonnet ./services/components/jaeger-collector.libsonnet ./services/components/loki-caches.libsonnet ./services/dex-template.jsonnet ./services/jaeger-template.jsonnet ./services/metric-federation-rule-template.jsonnet ./services/minio-template.jsonnet ./services/observatorium-traces-subscriptions-template.jsonnet ./services/observatorium-traces-subscriptions.libsonnet ./services/prometheus/remote-write-proxy.libsonnet ./services/sidecars/jaeger-agent.libsonnet ./services/sidecars/oauth-proxy.libsonnet ./services/sidecars/opa-ams.libsonnet ./services/sidecars/thanos-rule-syncer.libsonnet ./services/telemeter-template.jsonnet ./services/telemeter.libsonnet ./services/observatorium-logs-template-overwrites.libsonnet ./services/observatorium-logs-template.jsonnet ./services/observatorium-logs.libsonnet ./services/observatorium-tenants-template.jsonnet ./services/observatorium-traces-template.jsonnet ./services/observatorium-traces.libsonnet ./services/observatorium-metrics-template-overwrites.libsonnet ./services/observatorium-metrics-template.jsonnet ./services/parca-template.jsonnet ./services/observatorium-metrics.libsonnet ./services/observatorium-template.jsonnet ./services/observatorium.libsonnet
make clean
make[1]: Entering directory '/home/rexagod/repositories/configuration'
find resources/services -type f ! -name '*.yaml' -delete
find resources/observability/prometheusrules -type f ! -name '*.yaml' -delete
find resources/observability/grafana/observatorium -type f ! -name '*.yaml' -delete
find resources/observability/grafana/observatorium-logs -type f ! -name '*.yaml' -delete
find resources/services/telemeter-template.yaml -type f ! -name '*.yaml' -delete
make[1]: Leaving directory '/home/rexagod/repositories/configuration'
┌[rexagod@nebuchadnezzar] [/dev/pts/0] [a] 
└[~/repositories/configuration]> gss
┌[rexagod@nebuchadnezzar] [/dev/pts/0] [a] 
└[~/repositories/configuration]> gd aruniiird/add-advance-feature-metric-to-telemetri-server 
```

**Comment by rexagod** [comment]
Same thing on `make clean && make all`.

**Comment by rexagod** [comment]
Doing an `rm resources/services/telemeter-template.yaml && make manifests && make all` seems to work.

**Comment by rexagod** [comment]
@matej-g I've seem this happen quite often, where we have to manually remove the telemeter template and then run `make manifest && make all` for the diff to be consistent. 

Should this be added to the `manifest` target?

**Comment by aruniiird** [comment]
Thanks @matej-g , @rexagod ...

I've ran `make manifests` target and submitted the changes.
One thing noticed is, all the contents in file : `resources/services/metric-federation-rule-template.yaml` is now cleaned out and `null` is added to that file. Let me know if I missed something.

**Comment by rexagod** [comment]
@aruniiird Just curious, did the `make manifest` command work for you on the first go, or did you have to remove the file first?

**Comment by aruniiird** [comment]
About the file `metric-federation-rule-template.yaml` being null, that was an issue on getting the raw manifest file from `cluster-monitoring-operator` repo (https://raw.githubusercontent.com/openshift/cluster-monitoring-operator/master/manifests/0000_50_cluster-monitoring-operator_04-config.yaml). Fixed it.

> @aruniiird Just curious, did the `make manifest` command work for you on the first go, or did you have to remove the file first?

@rexagod , I had to remove the file manually and then run the `make manifests` to get correct result

**Comment by aruniiird** [comment]
@matej-g , can you please take a look...

**Comment by matej-g** [comment]
@aruniiird @rexagod Thanks, this looks good now. I tried it now and you're right, this seemed to have been problem previously where we had to remove generated manifests for targets to work properly. I'll take a look. Sorry for the inconvenience!

**Review by matej-g — APPROVED** [review]

**Pull request merged**
