### PR TITLE
Add support to deploy logs on OCP cluster

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR adds support to deploy `observatorium-logs` on OCP cluster via launch script.

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
Looks good to me. Is this already integrated in the ci runs here?

**Comment by vprashar2929** [comment]
No @periklis currently CI only deploy's RHOBS metrics part. After this PR I am planning to add logs to CI as well

**Comment by periklis** [comment]
> No @periklis currently CI only deploy's RHOBS metrics part. After this PR I am planning to add logs to CI as well

So you verified this only locally?

**Review by periklis — APPROVED** [review]

**Comment by vprashar2929** [comment]
Yes on OCP cluster the components are deployed successfully.

**Pull request merged**
