### PR TITLE
Observatorium traces service monitoring and dashboads

### PR DESCRIPTION
**Pull request by rubenvp8510**
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@frzifus @pavolloffay please review.

**Comment by pavolloffay** [comment]
Do you have screenshots with dashboards?

**Comment by frzifus** [comment]
or could you deploy it to RHOBS-Testing so that we can visit the dashboards?

**Comment by rubenvp8510** [comment]
OTel collector dashboard:
Screenshot from 2022-10-09 23-56-30
Screenshot from 2022-10-09 23-56-19

Jaeger dashboard:
Screenshot from 2022-10-10 00-03-25

**Review by frzifus — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]

**Comment by douglascamata** [comment]
Looks like this PR broke the build of the `main` branch due to some missing pod monitors in the general YAML files for tracing (cc @pavolloffay): https://github.com/rhobs/configuration/actions/runs/3292008153/jobs/5426869713.

**Pull request merged**
