### PR TITLE
Add row in instance utilization dashboard for Thanos Receive

### PR DESCRIPTION
**Pull request by douglascamata**
I'm planning to follow up with a PR allowing the `job` to be a dashboard variable and used in all the charts. This should help with filtering information.

### CODE REVIEW

**Comment by coleenquadros** [comment]
LGTM

I have created functions for the common resource utlization panels(memory,n/w,cpu,restarts) so that they are not repeated. If you'd like you can add them to your diff and I can update my branch later

https://github.com/rhobs/configuration/pull/535/files

**Comment by douglascamata** [comment]
@coleenquadros hummm, I see. I predicted we would be better off with helpers for some charts that will be repeated. But introducing them before we finish the creation of all the rows would case conflicts that can be potentially difficult to solve. 

I propose that we finish the implementation of the rows and then start refactoring. What do you think, @coleenquadros?

**Review by coleenquadros — APPROVED** [review]
Lgtm

**Review by saswatamcode — APPROVED** [review]
LGTM!

**Review by coleenquadros — APPROVED** [review]

**Pull request merged**
