### PR TITLE
MCO-371: Add os_image_url_override metric to allowlist

### PR DESCRIPTION
**Pull request by sinnykumari**
os_image_url_override:sum telemetry data will be added as part of https://github.com/openshift/cluster-monitoring-operator/pull/1784

### CODE REVIEW

**Comment by sinnykumari** [comment]
Putting hold until https://github.com/openshift/cluster-monitoring-operator/pull/1784 get merged
/hold

**Comment by sinnykumari** [comment]
Not that https://github.com/openshift/cluster-monitoring-operator/pull/1784 has been merged, removing hold. This is ready for review
/hold cancel

**Comment by sinnykumari** [comment]
can someone please review this.
tagging some of you based on recent people who reviewed changes to these files.
/cc @matej-g @bwplotka

**Review by jessicalins — APPROVED** [review]
LGTM

**Pull request merged**
