### PR TITLE
Add datasource and namespace parameters for loki overview dashboard

### PR DESCRIPTION
**Pull request by periklis**
The "Loki Overview" dashboard is a simplified version of the "Loki Operational" dashboard to monitor Loki clusters that use memberlist and boltdb-shipper for operations. The PR adds the missing parameters datasource and namepace to enable usage on multiple environments (i.e. staging, testing, production)

### CODE REVIEW

**Comment by douglascamata** [comment]
Does `observability/observatorium-logs/loki-overview.libsonnet` come from some sort of automation? 🤔 

Bit tough to review all the changes, so I would like to know how it's being maintained.

**Comment by periklis** [comment]
> Does `observability/observatorium-logs/loki-overview.libsonnet` come from some sort of automation? thinking
> 
> Bit tough to review all the changes, so I would like to know how it's being maintained.

Currently it is still developed by hand on Grafana and re-exported into json.

**Comment by periklis** [comment]
If that helps, this is how the board looks right now:
image

And this is after this change is applied:
image
image
image
image

**Review by douglascamata — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
