### PR TITLE
Add post deploy job

### PR DESCRIPTION
**Pull request by matej-g**
Signed-off-by: Matej Gera <matejgera@gmail.com>

This PR adds a bare-bone post deploy job to set up the initial configuration for post deploy E2E checks.

This will still require changes on the AppSRE Interface as well that will follow in a separate MR.

Related JIRA ticket: https://issues.redhat.com/browse/MON-1824

### CODE REVIEW

**Review by moadz — APPROVED** [review]
LGTM, would be great to get some details on what the e2e test is going to be.

**Review by PhilipGough — APPROVED** [review]
lgtm

**Review by jessicalins — APPROVED** [review]
:rocket:

**Review by bwplotka — APPROVED** [review]
Sweeet! Amazing 💪🏽

**Pull request merged**
